import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/sidebar/sidebar";


export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};


export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className="w-screen h-screen"
			>
				<div className="flex flex-row">
					<div className="basis-1/3 max-w-[300px]">
						<Sidebar />
					</div>
					<div className="flex-grow">
						{children}
					</div>
				</div>
			</body>
		</html>
	);
}
